version: '3'

services:
  web:
    container_name: simplemation-site
    image: simplemation-site
    build: .
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`simplemation.com.br`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.routers.web.tls=true"

networks:
  proxy:
    external: true